const express=require('express');const multer=require('multer');const fs=require('fs');const path=require('path');const {requireAdmin}=require('./adminAuth');const {processPdf}=require('./pdfProcessor');const {run,all,get}=require('./voterDatabase');
const router=express.Router();const upload=multer({storage:multer.memoryStorage(),limits:{files:100,fileSize:50*1024*1024},fileFilter:(req,f,cb)=>cb(null,f.mimetype==='application/pdf')});const jobs=new Map();
router.post('/upload',requireAdmin,upload.array('files',100),async(req,res)=>{const files=req.files||[];const id=Date.now().toString(36);jobs.set(id,{total:files.length,processed:0,records:0,failures:0,status:'processing'});res.status(202).json({jobId:id,total:files.length});(async()=>{for(const f of files){let doc=0;try{const now=new Date().toISOString();const dir=path.join(__dirname,'storage','pdfs');fs.mkdirSync(dir,{recursive:true});const stored=path.join(dir,`${Date.now()}-${f.originalname.replace(/[^\w.\-\u0980-\u09ff]/g,'_')}`);fs.writeFileSync(stored,f.buffer);const d=await run('INSERT INTO documents(filename,stored_path,status,uploaded_at) VALUES(?,?,?,?)',[f.originalname,stored,'processing',now]);doc=d.lastID;const p=await processPdf(f.buffer,f.originalname);for(const r of p.records)await run(`INSERT INTO voter_records(document_id,voter_id,serial_no,name,father_name,mother_name,birth_date,gender,occupation,address,village,ward,union_name,upazila,district,division,post_code,pdf_filename,page_number,raw_text,confidence,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[doc,r.voter_id,r.serial_no,r.name,r.father_name,r.mother_name,r.birth_date,r.gender,r.occupation,r.address,r.village,r.ward,r.union_name,r.upazila,r.district,r.division,r.post_code,f.originalname,r.page_number,r.raw_text,r.confidence,now]);await run('UPDATE documents SET page_count=?,status=?,ocr_used=? WHERE id=?',[p.pageCount,'completed',p.ocrUsed?1:0,doc]);jobs.get(id).records+=p.records.length;}catch(e){jobs.get(id).failures++;if(doc)await run('UPDATE documents SET status=?,error_msg=? WHERE id=?',['failed',String(e.message),doc]);}jobs.get(id).processed++;}jobs.get(id).status='completed';})();});
router.get('/upload/:id',requireAdmin,(req,res)=>res.json(jobs.get(req.params.id)||{error:'Job not found'}));
function filter(q){const w=[],v=[];if(q.q){const t=`%${q.q}%`;w.push('(name LIKE ? OR father_name LIKE ? OR mother_name LIKE ? OR voter_id LIKE ? OR district LIKE ? OR address LIKE ?)');v.push(t,t,t,t,t,t);}for(const f of ['name','father_name','mother_name','voter_id','district','upazila','union_name','ward','occupation'])if(q[f]){w.push(`${f} LIKE ?`);v.push(`%${q[f]}%`);}if(q.gender){w.push('gender=?');v.push(q.gender);}if(q.page_number){w.push('page_number=?');v.push(Number(q.page_number));}return {where:w.length?' WHERE '+w.join(' AND '):'',values:v};}
router.get('/records',requireAdmin,async(req,res)=>{const page=Math.max(1,+req.query.page||1),size=Math.min(200,Math.max(1,+req.query.page_size||50));const f=filter(req.query);const total=(await get(`SELECT COUNT(*) total FROM voter_records${f.where}`,f.values)).total;const records=await all(`SELECT * FROM voter_records${f.where} ORDER BY id DESC LIMIT ? OFFSET ?`,[...f.values,size,(page-1)*size]);res.json({records,total_count:total,page,page_size:size,total_pages:Math.ceil(total/size)});});
router.get('/dashboard',requireAdmin,async(req,res)=>{const total=(await get('SELECT COUNT(*) total FROM voter_records')).total;const pdfs=(await get('SELECT COUNT(*) total FROM documents')).total;const districts=await all("SELECT COALESCE(district,'Unknown') name,COUNT(*) count FROM voter_records GROUP BY district ORDER BY count DESC LIMIT 8");const occupations=await all("SELECT COALESCE(occupation,'Unknown') name,COUNT(*) count FROM voter_records GROUP BY occupation ORDER BY count DESC LIMIT 8");const gender=await all("SELECT COALESCE(gender,'Unknown') name,COUNT(*) count FROM voter_records GROUP BY gender ORDER BY count DESC");res.json({total_pdfs:pdfs,total_records:total,top_districts:districts,top_occupations:occupations,gender_breakdown:gender});});
function csv(rows){const fields=['voter_id','serial_no','name','father_name','mother_name','birth_date','gender','occupation','address','village','ward','union_name','upazila','district','division','post_code','pdf_filename','page_number'];const q=x=>`"${String(x??'').replace(/"/g,'""')}"`;return fields.join(',')+'\n'+rows.map(r=>fields.map(f=>q(r[f])).join(',')).join('\n');}
router.get('/export/csv',requireAdmin,async(req,res)=>{const f=filter(req.query),rows=await all(`SELECT * FROM voter_records${f.where} ORDER BY id DESC`,f.values);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="voter-records.csv"');res.send('\ufeff'+csv(rows));});
router.get('/export/excel',requireAdmin,async(req,res)=>{const f=filter(req.query),rows=await all(`SELECT * FROM voter_records${f.where} ORDER BY id DESC`,f.values);const fields=['voter_id','serial_no','name','father_name','mother_name','birth_date','gender','occupation','address','village','ward','union_name','upazila','district','division','post_code','pdf_filename','page_number'];const e=x=>String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Voters"><Table><Row>${fields.map(x=>`<Cell><Data ss:Type="String">${e(x)}</Data></Cell>`).join('')}</Row>${rows.map(r=>`<Row>${fields.map(x=>`<Cell><Data ss:Type="String">${e(r[x])}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`;res.setHeader('Content-Type','application/vnd.ms-excel');res.setHeader('Content-Disposition','attachment; filename="voter-records.xls"');res.send(xml);});
module.exports=router;
