const LABELS = {
  voter_id:[/ভোটার\s*(?:নং|নম্বর)/i,/NID\s*(?:No|Number)?/i,/voter\s*id/i], serial_no:[/ক্রমিক/i,/serial/i], name:[/^নাম\s*[:：-]?/im,/^name\s*[:：-]?/im], father_name:[/পিতা\s*[:：-]?/im,/father(?:'s)?\s*name\s*[:：-]?/im], mother_name:[/মাতা\s*[:：-]?/im,/mother(?:'s)?\s*name\s*[:：-]?/im], birth_date:[/জন্ম\s*তারিখ\s*[:：-]?/im,/DOB\s*[:：-]?/im], occupation:[/পেশা\s*[:：-]?/im,/occupation\s*[:：-]?/im], gender:[/লিঙ্গ\s*[:：-]?/im,/gender\s*[:：-]?/im], address:[/ঠিকানা\s*[:：-]?/im,/address\s*[:：-]?/im], ward:[/ওয়ার্ড\s*(?:নং|নম্বর)?\s*[:：-]?/im,/ward\s*(?:no|number)?\s*[:：-]?/im], union_name:[/ইউনিয়ন\s*[:：-]?/im,/union\s*[:：-]?/im], upazila:[/উপজেলা\s*[:：-]?/im,/upazila\s*[:：-]?/im], district:[/জেলা\s*[:：-]?/im,/district\s*[:：-]?/im], division:[/বিভাগ\s*[:：-]?/im,/division\s*[:：-]?/im], post_code:[/পোস্ট\s*কোড\s*[:：-]?/im,/post\s*code\s*[:：-]?/im]};
function clean(s){return String(s||'').replace(/[\t ]+/g,' ').replace(/^\s+|\s+$/g,'').replace(/[|]+$/,'').trim();}
function normalizeGender(v){const s=clean(v).toLowerCase();if(/পুরুষ|male|m\b/.test(s))return 'পুরুষ';if(/মহিলা|নারী|female|f\b/.test(s))return 'মহিলা';return clean(v);}
function valueAfter(lines, patterns, i){const line=lines[i];for(const p of patterns){const m=line.match(p);if(m){const rest=clean(line.slice(m[0].length));if(rest)return rest;return clean(lines[i+1]);}}return '';}
function parseRecord(lines, raw){const r={};for(const [field,pats] of Object.entries(LABELS)){for(let i=0;i<lines.length;i++){const v=valueAfter(lines,pats,i);if(v){r[field]=v;break;}}}r.gender=normalizeGender(r.gender);r.raw_text=raw;r.confidence=Object.keys(LABELS).filter(k=>r[k]).length/Object.keys(LABELS).length;return r;}
function splitVoters(text){const lines=text.split(/\r?\n/).map(clean).filter(Boolean);const starts=[];lines.forEach((line,i)=>{if(/^(?:ক্রমিক\s*)?[০-৯0-9]{1,6}[.)\-:]?$/.test(line))starts.push(i);});if(starts.length<2)return [lines.join('\n')];return starts.map((s,i)=>lines.slice(s,starts[i+1]||lines.length).join('\n'));}
function parsePage(text){return splitVoters(text).map(raw=>parseRecord(raw.split(/\r?\n/),raw));}
module.exports={parsePage,splitVoters,normalizeGender};
